create type "public"."patient_status" as enum ('PENDING', 'ADMITTED', 'DISABLED');


  create table "public"."dishes_allergens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dish_id" uuid,
    "allergen_id" bigint
      );


alter table "public"."dishes_allergens" enable row level security;

alter table "public"."patients" alter column "status" drop default;

alter table "public"."patients" alter column "status" set data type public.patient_status using "status"::public.patient_status;

CREATE UNIQUE INDEX dishes_allergens_pkey ON public.dishes_allergens USING btree (id);

alter table "public"."dishes_allergens" add constraint "dishes_allergens_pkey" PRIMARY KEY using index "dishes_allergens_pkey";

alter table "public"."dishes_allergens" add constraint "dishes_allergens_allergen_id_fkey" FOREIGN KEY (allergen_id) REFERENCES public.allergens(id) not valid;

alter table "public"."dishes_allergens" validate constraint "dishes_allergens_allergen_id_fkey";

alter table "public"."dishes_allergens" add constraint "dishes_allergens_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES public.dishes(id) ON DELETE CASCADE not valid;

alter table "public"."dishes_allergens" validate constraint "dishes_allergens_dish_id_fkey";

grant delete on table "public"."dishes_allergens" to "anon";

grant insert on table "public"."dishes_allergens" to "anon";

grant references on table "public"."dishes_allergens" to "anon";

grant select on table "public"."dishes_allergens" to "anon";

grant trigger on table "public"."dishes_allergens" to "anon";

grant truncate on table "public"."dishes_allergens" to "anon";

grant update on table "public"."dishes_allergens" to "anon";

grant delete on table "public"."dishes_allergens" to "authenticated";

grant insert on table "public"."dishes_allergens" to "authenticated";

grant references on table "public"."dishes_allergens" to "authenticated";

grant select on table "public"."dishes_allergens" to "authenticated";

grant trigger on table "public"."dishes_allergens" to "authenticated";

grant truncate on table "public"."dishes_allergens" to "authenticated";

grant update on table "public"."dishes_allergens" to "authenticated";

grant delete on table "public"."dishes_allergens" to "postgres";

grant insert on table "public"."dishes_allergens" to "postgres";

grant references on table "public"."dishes_allergens" to "postgres";

grant select on table "public"."dishes_allergens" to "postgres";

grant trigger on table "public"."dishes_allergens" to "postgres";

grant truncate on table "public"."dishes_allergens" to "postgres";

grant update on table "public"."dishes_allergens" to "postgres";

grant delete on table "public"."dishes_allergens" to "service_role";

grant insert on table "public"."dishes_allergens" to "service_role";

grant references on table "public"."dishes_allergens" to "service_role";

grant select on table "public"."dishes_allergens" to "service_role";

grant trigger on table "public"."dishes_allergens" to "service_role";

grant truncate on table "public"."dishes_allergens" to "service_role";

grant update on table "public"."dishes_allergens" to "service_role";


