


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."patient_status" AS ENUM (
    'PENDING',
    'ADMITTED',
    'DISABLED'
);


ALTER TYPE "public"."patient_status" OWNER TO "postgres";


CREATE TYPE "public"."plat" AS ENUM (
    'ENTREE',
    'PLAT',
    'DESSERT'
);


ALTER TYPE "public"."plat" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Logique automatique basée sur l'email pour Joela & Rasam
  IF new.email = 'rasamimananajoela@gmail.com' THEN
    INSERT INTO public.profiles (id, full_name, role) VALUES (new.id, 'Chef Rasam', 'KITCHEN');
  ELSIF new.email = 'joela.rasam@gmail.com' THEN
    INSERT INTO public.profiles (id, full_name, role) VALUES (new.id, 'Dr. Joela', 'MEDICAL');
  ELSE
    -- Par défaut, tout le monde est MEDICAL (ou selon logique métier)
    INSERT INTO public.profiles (id, full_name, role) VALUES (new.id, 'Nouvel Utilisateur', 'MEDICAL');
  END IF;
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."allergens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."allergens" OWNER TO "postgres";


ALTER TABLE "public"."allergens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."allergens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dishes" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "category" "text" NOT NULL,
    "description" "text",
    "allergens" "text"[] DEFAULT '{}'::"text"[],
    "nutritional_info" "jsonb" DEFAULT '{"calories": 0}'::"jsonb",
    "image_url" "text",
    "available" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "recipe" "jsonb" DEFAULT '[]'::"jsonb",
    CONSTRAINT "dishes_category_check" CHECK (("category" = ANY (ARRAY['ENTREE'::"text", 'PLAT'::"text", 'DESSERT'::"text"])))
);


ALTER TABLE "public"."dishes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dishes_allergens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "dish_id" "uuid",
    "allergen_id" bigint
);


ALTER TABLE "public"."dishes_allergens" OWNER TO "postgres";


ALTER TABLE "public"."dishes_allergens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dishes_allergens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ingredients" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "default_unit" "text" DEFAULT 'g'::"text",
    "allergen" "text"
);


ALTER TABLE "public"."ingredients" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meal_dishes" (
    "meal_id" "uuid" NOT NULL,
    "dish_id" "uuid" NOT NULL
);


ALTER TABLE "public"."meal_dishes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meals" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "day" "text" NOT NULL,
    "meal_type" "text" NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "meals_meal_type_check" CHECK (("meal_type" = ANY (ARRAY['Petit Déjeuner'::"text", 'Déjeuner'::"text", 'Dîner'::"text"])))
);


ALTER TABLE "public"."meals" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."patients" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "room" "text" NOT NULL,
    "service" "text" NOT NULL,
    "allergies" "text"[] DEFAULT '{}'::"text"[],
    "dietary_restrictions" "text"[] DEFAULT '{}'::"text"[],
    "status" "public"."patient_status" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."patients" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."patients_allergens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "patient_id" "uuid",
    "allergen_id" bigint
);


ALTER TABLE "public"."patients_allergens" OWNER TO "postgres";


ALTER TABLE "public"."patients_allergens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."patients_allergens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "role" "text" DEFAULT 'MEDICAL'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['MEDICAL'::"text", 'KITCHEN'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE ONLY "public"."allergens"
    ADD CONSTRAINT "allergens_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."allergens"
    ADD CONSTRAINT "allergens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dishes_allergens"
    ADD CONSTRAINT "dishes_allergens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dishes"
    ADD CONSTRAINT "dishes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meal_dishes"
    ADD CONSTRAINT "meal_dishes_pkey" PRIMARY KEY ("meal_id", "dish_id");



ALTER TABLE ONLY "public"."meals"
    ADD CONSTRAINT "meals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."patients_allergens"
    ADD CONSTRAINT "patients_allergens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."patients"
    ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dishes_allergens"
    ADD CONSTRAINT "dishes_allergens_allergen_id_fkey" FOREIGN KEY ("allergen_id") REFERENCES "public"."allergens"("id");



ALTER TABLE ONLY "public"."dishes_allergens"
    ADD CONSTRAINT "dishes_allergens_dish_id_fkey" FOREIGN KEY ("dish_id") REFERENCES "public"."dishes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_allergen_fkey" FOREIGN KEY ("allergen") REFERENCES "public"."allergens"("name") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."meal_dishes"
    ADD CONSTRAINT "meal_dishes_meal_id_fkey" FOREIGN KEY ("meal_id") REFERENCES "public"."meals"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."patients_allergens"
    ADD CONSTRAINT "patients_allergens_allergen_id_fkey" FOREIGN KEY ("allergen_id") REFERENCES "public"."allergens"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."patients_allergens"
    ADD CONSTRAINT "patients_allergens_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow read access to authenticated users" ON "public"."meal_dishes" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Allow read access to authenticated users" ON "public"."meals" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Allow write access to authenticated users" ON "public"."meal_dishes" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Allow write access to authenticated users" ON "public"."meals" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can insert patients" ON "public"."patients" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can manage allergens" ON "public"."allergens" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can manage dishes" ON "public"."dishes" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can manage ingredients" ON "public"."ingredients" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can read allergens" ON "public"."allergens" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can read dishes" ON "public"."dishes" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can read ingredients" ON "public"."ingredients" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can read patients" ON "public"."patients" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Authenticated users can update patients" ON "public"."patients" FOR UPDATE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Public can read dishes" ON "public"."dishes" FOR SELECT USING (true);



CREATE POLICY "Public can read patients" ON "public"."patients" FOR SELECT USING (true);



CREATE POLICY "Users can view own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."allergens" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dishes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dishes_allergens" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "enable update for own information" ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."ingredients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meal_dishes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."patients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."patients_allergens" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."allergens" TO "anon";
GRANT ALL ON TABLE "public"."allergens" TO "authenticated";
GRANT ALL ON TABLE "public"."allergens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."allergens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."allergens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."allergens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dishes" TO "anon";
GRANT ALL ON TABLE "public"."dishes" TO "authenticated";
GRANT ALL ON TABLE "public"."dishes" TO "service_role";



GRANT ALL ON TABLE "public"."dishes_allergens" TO "anon";
GRANT ALL ON TABLE "public"."dishes_allergens" TO "authenticated";
GRANT ALL ON TABLE "public"."dishes_allergens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dishes_allergens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dishes_allergens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dishes_allergens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ingredients" TO "anon";
GRANT ALL ON TABLE "public"."ingredients" TO "authenticated";
GRANT ALL ON TABLE "public"."ingredients" TO "service_role";



GRANT ALL ON TABLE "public"."meal_dishes" TO "anon";
GRANT ALL ON TABLE "public"."meal_dishes" TO "authenticated";
GRANT ALL ON TABLE "public"."meal_dishes" TO "service_role";



GRANT ALL ON TABLE "public"."meals" TO "anon";
GRANT ALL ON TABLE "public"."meals" TO "authenticated";
GRANT ALL ON TABLE "public"."meals" TO "service_role";



GRANT ALL ON TABLE "public"."patients" TO "anon";
GRANT ALL ON TABLE "public"."patients" TO "authenticated";
GRANT ALL ON TABLE "public"."patients" TO "service_role";



GRANT ALL ON TABLE "public"."patients_allergens" TO "anon";
GRANT ALL ON TABLE "public"."patients_allergens" TO "authenticated";
GRANT ALL ON TABLE "public"."patients_allergens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."patients_allergens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."patients_allergens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."patients_allergens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


