
  create table "public"."hospital_services" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."hospital_services" enable row level security;


  create table "public"."menu_planning" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "week_date" date not null,
    "day_of_week" smallint not null,
    "meal_type" text not null,
    "dish_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."menu_planning" enable row level security;

alter table "public"."dishes" add column "is_breakfast" boolean not null default false;

CREATE UNIQUE INDEX hospital_services_pkey ON public.hospital_services USING btree (id);

CREATE INDEX idx_menu_planning_dish ON public.menu_planning USING btree (dish_id);

CREATE INDEX idx_menu_planning_week ON public.menu_planning USING btree (week_date, day_of_week);

CREATE UNIQUE INDEX menu_planning_pkey ON public.menu_planning USING btree (id);

CREATE UNIQUE INDEX menu_planning_week_date_day_of_week_meal_type_dish_id_key ON public.menu_planning USING btree (week_date, day_of_week, meal_type, dish_id);

alter table "public"."hospital_services" add constraint "hospital_services_pkey" PRIMARY KEY using index "hospital_services_pkey";

alter table "public"."menu_planning" add constraint "menu_planning_pkey" PRIMARY KEY using index "menu_planning_pkey";

alter table "public"."menu_planning" add constraint "menu_planning_day_of_week_check" CHECK (((day_of_week >= 0) AND (day_of_week <= 6))) not valid;

alter table "public"."menu_planning" validate constraint "menu_planning_day_of_week_check";

alter table "public"."menu_planning" add constraint "menu_planning_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES public.dishes(id) ON DELETE CASCADE not valid;

alter table "public"."menu_planning" validate constraint "menu_planning_dish_id_fkey";

alter table "public"."menu_planning" add constraint "menu_planning_meal_type_check" CHECK ((meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text]))) not valid;

alter table "public"."menu_planning" validate constraint "menu_planning_meal_type_check";

alter table "public"."menu_planning" add constraint "menu_planning_week_date_day_of_week_meal_type_dish_id_key" UNIQUE using index "menu_planning_week_date_day_of_week_meal_type_dish_id_key";

grant delete on table "public"."hospital_services" to "anon";

grant insert on table "public"."hospital_services" to "anon";

grant references on table "public"."hospital_services" to "anon";

grant select on table "public"."hospital_services" to "anon";

grant trigger on table "public"."hospital_services" to "anon";

grant truncate on table "public"."hospital_services" to "anon";

grant update on table "public"."hospital_services" to "anon";

grant delete on table "public"."hospital_services" to "authenticated";

grant insert on table "public"."hospital_services" to "authenticated";

grant references on table "public"."hospital_services" to "authenticated";

grant select on table "public"."hospital_services" to "authenticated";

grant trigger on table "public"."hospital_services" to "authenticated";

grant truncate on table "public"."hospital_services" to "authenticated";

grant update on table "public"."hospital_services" to "authenticated";

grant delete on table "public"."hospital_services" to "postgres";

grant insert on table "public"."hospital_services" to "postgres";

grant references on table "public"."hospital_services" to "postgres";

grant select on table "public"."hospital_services" to "postgres";

grant trigger on table "public"."hospital_services" to "postgres";

grant truncate on table "public"."hospital_services" to "postgres";

grant update on table "public"."hospital_services" to "postgres";

grant delete on table "public"."hospital_services" to "service_role";

grant insert on table "public"."hospital_services" to "service_role";

grant references on table "public"."hospital_services" to "service_role";

grant select on table "public"."hospital_services" to "service_role";

grant trigger on table "public"."hospital_services" to "service_role";

grant truncate on table "public"."hospital_services" to "service_role";

grant update on table "public"."hospital_services" to "service_role";

grant delete on table "public"."menu_planning" to "anon";

grant insert on table "public"."menu_planning" to "anon";

grant references on table "public"."menu_planning" to "anon";

grant select on table "public"."menu_planning" to "anon";

grant trigger on table "public"."menu_planning" to "anon";

grant truncate on table "public"."menu_planning" to "anon";

grant update on table "public"."menu_planning" to "anon";

grant delete on table "public"."menu_planning" to "authenticated";

grant insert on table "public"."menu_planning" to "authenticated";

grant references on table "public"."menu_planning" to "authenticated";

grant select on table "public"."menu_planning" to "authenticated";

grant trigger on table "public"."menu_planning" to "authenticated";

grant truncate on table "public"."menu_planning" to "authenticated";

grant update on table "public"."menu_planning" to "authenticated";

grant delete on table "public"."menu_planning" to "postgres";

grant insert on table "public"."menu_planning" to "postgres";

grant references on table "public"."menu_planning" to "postgres";

grant select on table "public"."menu_planning" to "postgres";

grant trigger on table "public"."menu_planning" to "postgres";

grant truncate on table "public"."menu_planning" to "postgres";

grant update on table "public"."menu_planning" to "postgres";

grant delete on table "public"."menu_planning" to "service_role";

grant insert on table "public"."menu_planning" to "service_role";

grant references on table "public"."menu_planning" to "service_role";

grant select on table "public"."menu_planning" to "service_role";

grant trigger on table "public"."menu_planning" to "service_role";

grant truncate on table "public"."menu_planning" to "service_role";

grant update on table "public"."menu_planning" to "service_role";


  create policy "Enable crud for authenticated users only"
  on "public"."dishes_allergens"
  as permissive
  for all
  to authenticated
using (true);



  create policy "CRUD for auth users"
  on "public"."hospital_services"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."hospital_services"
  as permissive
  for select
  to public
using (true);



  create policy "Allow delete for kitchen staff"
  on "public"."menu_planning"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'KITCHEN'::public.profile_roles)))));



  create policy "Allow insert for kitchen staff"
  on "public"."menu_planning"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'KITCHEN'::public.profile_roles)))));



  create policy "Allow read access for authenticated users"
  on "public"."menu_planning"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow update for kitchen staff"
  on "public"."menu_planning"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'KITCHEN'::public.profile_roles)))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'KITCHEN'::public.profile_roles)))));



  create policy "Enable insert for authenticated users only"
  on "public"."patients_allergens"
  as permissive
  for all
  to authenticated
using (true);



