drop extension if exists "pg_net";


  create table "public"."allergens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
      );


alter table "public"."allergens" enable row level security;


  create table "public"."dishes" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "name" text not null,
    "category" text not null,
    "allergens" text[] default '{}'::text[],
    "nutritional_info" jsonb default '{"fat": 0, "carbs": 0, "protein": 0, "calories": 0}'::jsonb,
    "image_url" text,
    "description" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."dishes" enable row level security;


  create table "public"."meal_dishes" (
    "meal_id" uuid not null,
    "dish_id" uuid not null
      );


alter table "public"."meal_dishes" enable row level security;


  create table "public"."meals" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "day" text not null,
    "meal_type" text not null,
    "name" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."meals" enable row level security;


  create table "public"."patients" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "firstname" text not null,
    "lastname" text not null
      );


alter table "public"."patients" enable row level security;


  create table "public"."patients_allergens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "patient_id" uuid,
    "allergen_id" bigint
      );


alter table "public"."patients_allergens" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text,
    "role" text default 'MEDICAL'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX allergens_name_key ON public.allergens USING btree (name);

CREATE UNIQUE INDEX allergens_pkey ON public.allergens USING btree (id);

CREATE UNIQUE INDEX dishes_pkey ON public.dishes USING btree (id);

CREATE UNIQUE INDEX meal_dishes_pkey ON public.meal_dishes USING btree (meal_id, dish_id);

CREATE UNIQUE INDEX meals_pkey ON public.meals USING btree (id);

CREATE UNIQUE INDEX patients_allergens_pkey ON public.patients_allergens USING btree (id);

CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."allergens" add constraint "allergens_pkey" PRIMARY KEY using index "allergens_pkey";

alter table "public"."dishes" add constraint "dishes_pkey" PRIMARY KEY using index "dishes_pkey";

alter table "public"."meal_dishes" add constraint "meal_dishes_pkey" PRIMARY KEY using index "meal_dishes_pkey";

alter table "public"."meals" add constraint "meals_pkey" PRIMARY KEY using index "meals_pkey";

alter table "public"."patients" add constraint "patients_pkey" PRIMARY KEY using index "patients_pkey";

alter table "public"."patients_allergens" add constraint "patients_allergens_pkey" PRIMARY KEY using index "patients_allergens_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."allergens" add constraint "allergens_name_key" UNIQUE using index "allergens_name_key";

alter table "public"."dishes" add constraint "dishes_category_check" CHECK ((category = ANY (ARRAY['ENTREE'::text, 'PLAT'::text, 'DESSERT'::text]))) not valid;

alter table "public"."dishes" validate constraint "dishes_category_check";

alter table "public"."meal_dishes" add constraint "meal_dishes_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES public.dishes(id) ON DELETE CASCADE not valid;

alter table "public"."meal_dishes" validate constraint "meal_dishes_dish_id_fkey";

alter table "public"."meal_dishes" add constraint "meal_dishes_meal_id_fkey" FOREIGN KEY (meal_id) REFERENCES public.meals(id) ON DELETE CASCADE not valid;

alter table "public"."meal_dishes" validate constraint "meal_dishes_meal_id_fkey";

alter table "public"."meals" add constraint "meals_meal_type_check" CHECK ((meal_type = ANY (ARRAY['Petit Déjeuner'::text, 'Déjeuner'::text, 'Dîner'::text]))) not valid;

alter table "public"."meals" validate constraint "meals_meal_type_check";

alter table "public"."patients_allergens" add constraint "patients_allergens_allergen_id_fkey" FOREIGN KEY (allergen_id) REFERENCES public.allergens(id) ON DELETE CASCADE not valid;

alter table "public"."patients_allergens" validate constraint "patients_allergens_allergen_id_fkey";

alter table "public"."patients_allergens" add constraint "patients_allergens_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE not valid;

alter table "public"."patients_allergens" validate constraint "patients_allergens_patient_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['MEDICAL'::text, 'KITCHEN'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    COALESCE(new.raw_user_meta_data->>'role', 'MEDICAL') -- Default to MEDICAL if role not provided
  );
  RETURN new;
END;
$function$
;

grant delete on table "public"."allergens" to "anon";

grant insert on table "public"."allergens" to "anon";

grant references on table "public"."allergens" to "anon";

grant select on table "public"."allergens" to "anon";

grant trigger on table "public"."allergens" to "anon";

grant truncate on table "public"."allergens" to "anon";

grant update on table "public"."allergens" to "anon";

grant delete on table "public"."allergens" to "authenticated";

grant insert on table "public"."allergens" to "authenticated";

grant references on table "public"."allergens" to "authenticated";

grant select on table "public"."allergens" to "authenticated";

grant trigger on table "public"."allergens" to "authenticated";

grant truncate on table "public"."allergens" to "authenticated";

grant update on table "public"."allergens" to "authenticated";

grant delete on table "public"."allergens" to "service_role";

grant insert on table "public"."allergens" to "service_role";

grant references on table "public"."allergens" to "service_role";

grant select on table "public"."allergens" to "service_role";

grant trigger on table "public"."allergens" to "service_role";

grant truncate on table "public"."allergens" to "service_role";

grant update on table "public"."allergens" to "service_role";

grant delete on table "public"."dishes" to "anon";

grant insert on table "public"."dishes" to "anon";

grant references on table "public"."dishes" to "anon";

grant select on table "public"."dishes" to "anon";

grant trigger on table "public"."dishes" to "anon";

grant truncate on table "public"."dishes" to "anon";

grant update on table "public"."dishes" to "anon";

grant delete on table "public"."dishes" to "authenticated";

grant insert on table "public"."dishes" to "authenticated";

grant references on table "public"."dishes" to "authenticated";

grant select on table "public"."dishes" to "authenticated";

grant trigger on table "public"."dishes" to "authenticated";

grant truncate on table "public"."dishes" to "authenticated";

grant update on table "public"."dishes" to "authenticated";

grant delete on table "public"."dishes" to "service_role";

grant insert on table "public"."dishes" to "service_role";

grant references on table "public"."dishes" to "service_role";

grant select on table "public"."dishes" to "service_role";

grant trigger on table "public"."dishes" to "service_role";

grant truncate on table "public"."dishes" to "service_role";

grant update on table "public"."dishes" to "service_role";

grant delete on table "public"."meal_dishes" to "anon";

grant insert on table "public"."meal_dishes" to "anon";

grant references on table "public"."meal_dishes" to "anon";

grant select on table "public"."meal_dishes" to "anon";

grant trigger on table "public"."meal_dishes" to "anon";

grant truncate on table "public"."meal_dishes" to "anon";

grant update on table "public"."meal_dishes" to "anon";

grant delete on table "public"."meal_dishes" to "authenticated";

grant insert on table "public"."meal_dishes" to "authenticated";

grant references on table "public"."meal_dishes" to "authenticated";

grant select on table "public"."meal_dishes" to "authenticated";

grant trigger on table "public"."meal_dishes" to "authenticated";

grant truncate on table "public"."meal_dishes" to "authenticated";

grant update on table "public"."meal_dishes" to "authenticated";

grant delete on table "public"."meal_dishes" to "service_role";

grant insert on table "public"."meal_dishes" to "service_role";

grant references on table "public"."meal_dishes" to "service_role";

grant select on table "public"."meal_dishes" to "service_role";

grant trigger on table "public"."meal_dishes" to "service_role";

grant truncate on table "public"."meal_dishes" to "service_role";

grant update on table "public"."meal_dishes" to "service_role";

grant delete on table "public"."meals" to "anon";

grant insert on table "public"."meals" to "anon";

grant references on table "public"."meals" to "anon";

grant select on table "public"."meals" to "anon";

grant trigger on table "public"."meals" to "anon";

grant truncate on table "public"."meals" to "anon";

grant update on table "public"."meals" to "anon";

grant delete on table "public"."meals" to "authenticated";

grant insert on table "public"."meals" to "authenticated";

grant references on table "public"."meals" to "authenticated";

grant select on table "public"."meals" to "authenticated";

grant trigger on table "public"."meals" to "authenticated";

grant truncate on table "public"."meals" to "authenticated";

grant update on table "public"."meals" to "authenticated";

grant delete on table "public"."meals" to "service_role";

grant insert on table "public"."meals" to "service_role";

grant references on table "public"."meals" to "service_role";

grant select on table "public"."meals" to "service_role";

grant trigger on table "public"."meals" to "service_role";

grant truncate on table "public"."meals" to "service_role";

grant update on table "public"."meals" to "service_role";

grant delete on table "public"."patients" to "anon";

grant insert on table "public"."patients" to "anon";

grant references on table "public"."patients" to "anon";

grant select on table "public"."patients" to "anon";

grant trigger on table "public"."patients" to "anon";

grant truncate on table "public"."patients" to "anon";

grant update on table "public"."patients" to "anon";

grant delete on table "public"."patients" to "authenticated";

grant insert on table "public"."patients" to "authenticated";

grant references on table "public"."patients" to "authenticated";

grant select on table "public"."patients" to "authenticated";

grant trigger on table "public"."patients" to "authenticated";

grant truncate on table "public"."patients" to "authenticated";

grant update on table "public"."patients" to "authenticated";

grant delete on table "public"."patients" to "service_role";

grant insert on table "public"."patients" to "service_role";

grant references on table "public"."patients" to "service_role";

grant select on table "public"."patients" to "service_role";

grant trigger on table "public"."patients" to "service_role";

grant truncate on table "public"."patients" to "service_role";

grant update on table "public"."patients" to "service_role";

grant delete on table "public"."patients_allergens" to "anon";

grant insert on table "public"."patients_allergens" to "anon";

grant references on table "public"."patients_allergens" to "anon";

grant select on table "public"."patients_allergens" to "anon";

grant trigger on table "public"."patients_allergens" to "anon";

grant truncate on table "public"."patients_allergens" to "anon";

grant update on table "public"."patients_allergens" to "anon";

grant delete on table "public"."patients_allergens" to "authenticated";

grant insert on table "public"."patients_allergens" to "authenticated";

grant references on table "public"."patients_allergens" to "authenticated";

grant select on table "public"."patients_allergens" to "authenticated";

grant trigger on table "public"."patients_allergens" to "authenticated";

grant truncate on table "public"."patients_allergens" to "authenticated";

grant update on table "public"."patients_allergens" to "authenticated";

grant delete on table "public"."patients_allergens" to "service_role";

grant insert on table "public"."patients_allergens" to "service_role";

grant references on table "public"."patients_allergens" to "service_role";

grant select on table "public"."patients_allergens" to "service_role";

grant trigger on table "public"."patients_allergens" to "service_role";

grant truncate on table "public"."patients_allergens" to "service_role";

grant update on table "public"."patients_allergens" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Allow read access to authenticated users"
  on "public"."dishes"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow write access to authenticated users"
  on "public"."dishes"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow read access to authenticated users"
  on "public"."meal_dishes"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow write access to authenticated users"
  on "public"."meal_dishes"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow read access to authenticated users"
  on "public"."meals"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow write access to authenticated users"
  on "public"."meals"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow read access to authenticated users"
  on "public"."patients"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow write access to authenticated users"
  on "public"."patients"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


